name: flutter_eft
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.3.0
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  loading_animation_widget: ^1.2.0+1
  tbib_splash_screen: ^0.0.4
  flutter_spinkit: ^5.1.0
  keyboard_visibility: ^0.5.6
  flutter_svg: ^1.0.3
  sqflite: ^2.0.2+1
  json_annotation: ^4.5.0
  rflutter_alert: ^2.0.4
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  flutter_local_notifications: ^9.2.0
  path_provider: ^2.0.8
  http: ^0.13.4
  url_launcher: ^6.0.18
  get: ^4.6.1
  logger: ^1.0.0
  easy_separator: ^1.0.1
  blurhash_flutter: ^0.1.0
  google_fonts: ^2.2.0
  flutter_zoom_drawer: ^2.1.2
  liquid_pull_to_refresh: ^3.0.1
  shimmer: ^2.0.0
  flutter_native_splash: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/database/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf

tbib_splash_screen:
  color: "#ffffff"
